// Create a function multiplication that will receive 2 numbers as arguments, and return the result of the multiplication of those numbers.

const multiplication = (num1, num2) => num1 * num2;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
;
console.log(multiplication(8, 3));
